language: node_js

node_js:
  - '6'

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run test:ci
  - bash <(curl -s https://codecov.io/bash) -F unit
  - npm run test:ci-ie
  - bash <(curl -s https://codecov.io/bash) -F unit_ie